import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import 'capture_tables.dart';

// Generated by `dart run build_runner build` (Drift code-gen). This file does
// not exist until the generator runs in a Flutter/Dart environment — see the
// note at the bottom of this file.
part 'app_database.g.dart';

/// The device-local SQLite database (Drift).
///
/// F1 only owns the offline capture outbox ([LocalCaptures]); further tables
/// are added by later features via a bumped [schemaVersion] + migration.
@DriftDatabase(tables: [LocalCaptures])
class AppDatabase extends _$AppDatabase {
  /// Production constructor: opens a file-backed database in the app documents
  /// directory (lazily, off the UI isolate).
  AppDatabase() : super(_openConnection());

  /// Test/DI constructor: inject any [QueryExecutor], e.g. an in-memory
  /// `NativeDatabase.memory()` for fast, isolated unit tests.
  AppDatabase.withExecutor(super.executor);

  @override
  int get schemaVersion => 1;

  // --- Outbox queries used by CaptureRepository / SyncService ---------------

  /// All local captures, newest first. Used by the UI (observable stream).
  Stream<List<LocalCapture>> watchAllCaptures() {
    return (select(localCaptures)
          ..orderBy([
            (t) => OrderingTerm(
                  expression: t.createdAtLocal,
                  mode: OrderingMode.desc,
                ),
          ]))
        .watch();
  }

  /// One-shot read of all local captures, newest first.
  Future<List<LocalCapture>> allCaptures() {
    return (select(localCaptures)
          ..orderBy([
            (t) => OrderingTerm(
                  expression: t.createdAtLocal,
                  mode: OrderingMode.desc,
                ),
          ]))
        .get();
  }

  /// Read one capture by its client id, or `null` if it does not exist.
  Future<LocalCapture?> captureByClientId(String clientId) {
    return (select(localCaptures)
          ..where((t) => t.clientId.equals(clientId)))
        .getSingleOrNull();
  }

  /// Insert a new capture (optimistic save). Returns nothing; the caller owns
  /// the generated `clientId`.
  Future<void> insertCapture(LocalCapturesCompanion capture) {
    return into(localCaptures).insert(capture);
  }

  /// FIFO batch of captures eligible for a sync attempt (design.md §11.2).
  ///
  /// Eligible == still in the retryable `pending` state AND due
  /// (`nextAttemptAt` is null, i.e. never attempted, or already elapsed).
  /// `failed` rows (terminal 4xx) are intentionally excluded so validation
  /// errors are not retried automatically (R6.6).
  Future<List<LocalCapture>> pendingBatch(DateTime now, int limit) {
    return (select(localCaptures)
          ..where((t) =>
              t.syncState.equals(SyncState.pending) &
              (t.nextAttemptAt.isNull() |
                  t.nextAttemptAt.isSmallerOrEqualValue(now)))
          ..orderBy([
            (t) => OrderingTerm(
                  expression: t.createdAtLocal,
                  mode: OrderingMode.asc,
                ),
          ])
          ..limit(limit))
        .get();
  }

  /// Update just the sync-state of a capture (e.g. -> uploadingAudio/syncing).
  Future<void> setSyncState(String clientId, String state) {
    return (update(localCaptures)..where((t) => t.clientId.equals(clientId)))
        .write(LocalCapturesCompanion(syncState: Value(state)));
  }

  /// Persist the S3 `audio_ref` after the audio has been uploaded.
  Future<void> setAudioRef(String clientId, String audioRef) {
    return (update(localCaptures)..where((t) => t.clientId.equals(clientId)))
        .write(LocalCapturesCompanion(audioRef: Value(audioRef)));
  }

  /// Mark a capture as successfully synced and store the server `capture_id`.
  Future<void> markSynced(String clientId, String serverId) {
    return (update(localCaptures)..where((t) => t.clientId.equals(clientId)))
        .write(
      LocalCapturesCompanion(
        syncState: const Value(SyncState.synced),
        serverId: Value(serverId),
      ),
    );
  }

  /// Mark a capture as terminally failed (4xx validation) — no auto-retry.
  Future<void> markFailed(String clientId) {
    return (update(localCaptures)..where((t) => t.clientId.equals(clientId)))
        .write(
      const LocalCapturesCompanion(
        syncState: Value(SyncState.failed),
        nextAttemptAt: Value<DateTime?>(null),
      ),
    );
  }

  /// Schedule a transient-failure retry: bump the retry count, keep the row in
  /// the retryable `pending` state and set the next eligible attempt time.
  Future<void> scheduleRetry(
    String clientId,
    int retryCount,
    DateTime nextAttemptAt,
  ) {
    return (update(localCaptures)..where((t) => t.clientId.equals(clientId)))
        .write(
      LocalCapturesCompanion(
        syncState: const Value(SyncState.pending),
        retryCount: Value(retryCount),
        nextAttemptAt: Value(nextAttemptAt),
      ),
    );
  }
}

/// Lazily open a file-backed SQLite database in the app documents directory.
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'mindos.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}

// ---------------------------------------------------------------------------
// CODE-GEN NOTE
// ---------------------------------------------------------------------------
// The `part 'app_database.g.dart'` above is produced by Drift's build_runner.
// It is NOT checked in and MUST be generated before this compiles:
//
//     cd apps/mobile
//     flutter pub get
//     dart run build_runner build --delete-conflicting-outputs
//
// This repository does not ship the generated file, and the sandbox has no
// Flutter/Dart SDK, so `flutter analyze` / `flutter test` cannot run here.
// ---------------------------------------------------------------------------
